# Generated by Django 3.2.9 on 2022-03-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palindrome',
            new_name='PalindromeModel',
        ),
    ]
