# Generated by Django 3.2.9 on 2022-03-19 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0002_rename_palindrome_palindromemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='palindromemodel',
            name='added_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
