# Generated by Django 3.2.9 on 2022-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0003_palindromemodel_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palindromemodel',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
